name: release
on:
  release:
    types:
      - published
permissions:
  contents: read
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: pip install flit
      - name: Upload
        env:
          FLIT_USERNAME: "__token__"
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: flit publish
